### PR TITLE
Update Enumerations.md

### PR DESCRIPTION
**Pull request by Gudi-24**
I think that here the object reference should be passed instead of the id (attribute value). Otherwise it wouldn’t be type-safe anymore and somehow destroy the object pattern approach.
Maybe it is only a typo, because later it is written correctly.

### CODE REVIEW

**Comment by pokrakam** [comment]
I think the current state is correct, and consistent with the other examples. In all examples `log_contains( )` receives a parameter of type `symsgty`. 
With the object pattern the attribute is an instance. To get the message type - as with the other examples - we need to get the instance's value attribute. 

I must admit that I personally don't like this pattern because this exact construct in ABAP feels cumbersome and awkward to me. It took me several reads to understand it.

**Comment by pokrakam** [comment]
I do understand the pattern. The reason I said that it is consistent with the other examples is that all examples refer to the literal value, and, as Florian pointed out, the consumer also needs to be aware of this.

If we go down the object route, then the example should be expanded to include the consumer, asFlorian suggested. We won't fully get away from the multi-level handling because then the handler code has to retrieve the value:
```ABAP
METHOD log_contains. 
  LOOP AT messages into DATA(message). 
    IF message->type = i_message_severity->value. 
```
As this becomes difficult to retrofit into an existing code base, therefore (I assume) the example worked with the value, therefore I concluded that the example was correct.

I also agree that this pattern has merit; I was careful to say this construct feels cumbersome **in ABAP**. It's used in JS too, but it looks more natural because JS objects are more primitive and can be declared as literals. There's no executable code involved. 
But in ABAP having to code a constructor to instantiate an object for each value is overkill IMHO and just feels too contrived. I won't ignore it, but for me it's filed under "special use cases". 
I think using ENUMs - possibly as a class attribute - is a better alternative to type safety than the object pattern. But that's just my personal view which is always subject to change 🙂

**Review by N2oB6n-SAP — CHANGES_REQUESTED** [review]
I consider the object pattern a valuable hybrid because it addresses both the call for rigid type-safety in new signatures as well as offering a fallback to comply with legacy calls where signature refactoring would cascade into a lot of pain.

Please note that I have opened PR #293 to address the benefits of native ENUM - I agree with @pokrakam on the assessment that providing these as class attributes is superior :)

Nevertheless I do understand the confusion and believe this PR here is not rendered obsolete: I agree with @HrFlorianHoffmann and **recommend we add the reasoning why and when `...-value` has to be used** (i.e. to comply with legacy signatures) to clarify.

**Review by N2oB6n-SAP — APPROVED** [review]
My latest commit addresses the confusion about the meaning of `...->value`.

**Review by sautermi0 — APPROVED** [review]

**Review by KlausHaeuptleSAP — APPROVED** [review]

**Review by rdibbern — APPROVED** [review]

**Review by cribuc — APPROVED** [review]

**Pull request merged**
