### PR TITLE
New section "Use simple types"

### PR DESCRIPTION
**Pull request by jrgkraus**
See also https://blogs.sap.com/2020/03/25/the-use-simple-types-approach/

### CODE REVIEW

**Comment by mAltr** [comment]
For me it´s personally unclear why I should convert everything to string and lose all build in functions provided from se11. I understand the idea to make it more simple, like JavaScript, but the price losing type safty is for me to high. Type safty makes code more readable and more robust.

From you example:

types: 
    begin of material_fields,
        number type string,
        plant type string,
        description type string,
        stock type f,
        unit_of_measure type string,    
    end of material_fields.

In your type definition it is possible to write anything inside plant, even it is on db side defined as char4. How will you make sure, that it will only contain a char4? In case someone else will maintain your code, how will this person know, that only char4 values are correct?

**Comment by jrgkraus** [comment]
I understand your point. I admit that this is a price you pay following this practice. It may be useful letting the syntax checker control whether you pass the right variable to your call. But personally, I prefer unit tests to assert the correct functionality of my code. Moreover, the name of the variable should reflect its content. If you write 

```
  read_plant_data( material_description ).
``` 

The syntax checker would not complain, because everything is string. but It would be pretty obvious that something's wrong with your code.  Of course, if you use something like 

```
  read_plant_data( input_par ).
```
the syntax checker can do the job. However, if input_par contains a BUKRS, BWKEY with the right type, but the wrong content, you're lost.

Another point regarding numbers: There are so many DDIC types representing numbers, even with the same semantics that I really find it much easier to pass floats to and from my methods so I do not have to care if there is a MENG13, MENG17 or MENG13V in charge...

**Comment by jrgkraus** [comment]
I see 3 thumbs down, but no written motivation for them. I'm new to github... is this the normal procedure in this community?

**Comment by cgolde** [comment]
Hello, if you building small isolated applications, your idea is inline with other programming paradigms like JavaScript and would perfectly work. But coding in the SAP ecosystem is normally focused on business applications. I would value loosing the type-safety as a clear disadvantage of your proposal.
Since many other applications (like the gateway builder, CDS, BOPF and many more) rely in different extends on the meta data from the data dictionary, you would loose many possibilities for integrating with other applications or standard frameworks.
At least your database tables and external APIs should comply with DDIC for providing a clear usage contract on data types for others. But this would lead to mixing up different programming styles and contracts inside your application which I would not consider as clean code. This could eventually lead to even more confusion than figuring out the right DDIC type (or creating a new one) for your use cases. That’s why i have disliked your proposal.
Kind regards

**Pull request closed without merging**
