### PR TITLE
Fixed dead links to docs.abapgit.org in ABAPCodeReview.md

### PR DESCRIPTION
**Pull request by kjetil-kilhavn**
Links to abapGit documentation updated - and updated to not use file extensions as recommended in https://www.w3.org/Provider/Style/URI (Cool URIs don't change)

### CODE REVIEW

**Comment by ConjuringCoffee** [comment]
FYI this will be fixed in abapGit/docs.abapgit.org#138 which is why I closed my own pull request #328

**Comment by kjetil-kilhavn** [comment]
Yes, that's a dillemma. I found your PR after submitting mine (I just looked at open PRs first - which I must admit I will continue to do ... :-)
The site has been re-organized so the URLs **have** actually changed and the solution proposed for docs.abapgit.org is to re-create the old files and have them redirect to the new files. I don't know if that will solve the dead link issue also for links to anchors inside the file. 
In any case that's not quite the same as having URLs which don't change, so I'll leave this PR for now and let you and the other maintainers decide what to do. The changes here should be OK even if docs.abapgit.org implement redirection for the old URLs.

**Review by ConjuringCoffee — APPROVED** [review]
You have my blessing 😇

**Comment by kjetil-kilhavn** [comment]
It seems the build still fails for #325 - so the redirection solution deployed for docs.abapgit.org probably doesn't work for the link checker.

**Comment by bjoern-jueliger-sap** [comment]
> It seems the build still fails for #325 - so the redirection solution deployed for docs.abapgit.org probably doesn't work for the link checker.

The redirection works, the last run of the build job in #325 was older than the solution on abapGit's site being deployed. I've re-run the build job and it's green now.

**Review by xtough — APPROVED** [review]
Looks good to me. Thanks for the fix!

**Pull request merged**
