### PR TITLE
Static method calls

### PR DESCRIPTION
**Pull request by jordao76**
Clarify calling of static methods.

Resolves SAP/styleguides#210

### CODE REVIEW

**Comment by pokrakam** [comment]
Re. "_It's OK to call a static method of the same class without qualifying it within another static method._" 
Is it always? 
That was why I opened an issue rather than a PR, I'd like to get some input on this angle. Personally I think a static call in the same class should be fully qualified in many cases. It's easy to forward-navigate and think you're in an instance method. We should only drop the class name in obvious cases such as factory methods IMHO.

**Comment by jordao76** [comment]
>  whether we should fully qualify static calls of the same class within instance methods?

Yes that's what I implied, and I'm sorry I wasn't clear on that. I'll add it later on.

**Comment by HrFlorianHoffmann** [comment]
@jordao76 Are you still planning to add something?

**Comment by jordao76** [comment]
> @jordao76 Are you still planning to add something?

Yes, I'll try to get around to it next week.

**Comment by jordao76** [comment]
I'll create another pull request, since the merge of this one got out of whack

**Pull request closed without merging**
