### PR TITLE
docs: Remove IF block in CHECK vs. RETURN

### PR DESCRIPTION
**Pull request by mauriciolauffer**
It's not clean, it may not be clear, it adds unnecessary depth. If this a clean code guide, the suggested IF block has no place here as it's worse and dirtier than the other options.

### CODE REVIEW

**Comment by mauriciolauffer** [comment]
PS: thanks to Jelena for starting the discussion: https://twitter.com/JelenaAtLarge/status/1527775392790204416

**Comment by larshp** [comment]
#276

**Review by rdibbern — APPROVED** [review]

**Review by sautermi0 — CHANGES_REQUESTED** [review]
Instead of just removing this part, I would like keep it in the guide as an anti-pattern. 

Developers reading the guide will still have the idea to wrap the entire method content in an IF-statement and if we list it as an anti-pattern, it is clear that code should not be implemented like this. If we just delete it, it's not clear whether it's good or bad for readers.

**Review by N2oB6n-SAP — CHANGES_REQUESTED** [review]
Generally, I would agree with @sautermi0 on rather turning this into an anti-pattern code snippet than removing it altogether. Providing a counter-example and, ideally, providing arguments against it such as a reference to the "Keeping the nesting depth low" section sounds good to me.

Technically speaking, though, one might argue that **this ("why not to wrap") is a separate concern than the core idea of "CHECK vs. RETURN"**. The whole section deals with what is elsewhere called a _guard clause_. Any opinions on dealing with this seperately?

**Review by KlausHaeuptleSAP — APPROVED** [review]
Thanks! LGTM

**Review by sautermi0 — APPROVED** [review]

**Pull request merged**
