### PR TITLE
make online AsciiDoc more prominent

### PR DESCRIPTION
**Pull request by xtough**
feedback from readers

### CODE REVIEW

**Review by xtough — COMMENTED** [review]
@larshp FYI

**Comment by pokrakam** [comment]
Initial reaction is yes! but GitHub doesn't render plantUML. 
https://github.com/SAP/styleguides/blob/main/abap-code-review/src/scenarios.adoc
Either drop this change or add a caveat.

**Comment by nununo** [comment]
> Initial reaction is yes! but GitHub doesn't render plantUML.
> https://github.com/SAP/styleguides/blob/main/abap-code-review/src/scenarios.adoc
> Either drop this change or add a caveat.

Or... would it be feasible to use a PlantUML server and insert dynamic images next to the PlantUML code?

**Comment by xtough** [comment]
> Either drop this change or add a caveat.

Done. 

> Or... would it be feasible to use a PlantUML server and insert dynamic images next to the PlantUML code?

Not sure how to tweak GitHub AsciiDoc preview to replace PlantUML source with online content 😕

**Comment by larshp** [comment]
PlantUML: there are some hacks, but its all hacks

For reading, the PDF document is formatted, printable etc

**Comment by nununo** [comment]
I'm not saying it is a good solution. But it is a possible one:

PlantUML

**Comment by xtough** [comment]
I am not quite sure how you created the linked githubusercontent but I guess it will not be so easy to embed this into the Adoc preview, right?

I would suggest to keep this PR #203 small and open a new issue instead on dynamically generating PlantUML for the previews. OK?

**Pull request merged**
