### PR TITLE
Change wording of rule to consider READ-ONLY attributes

### PR DESCRIPTION
**Pull request by ConjuringCoffee**
Our discussion in #299 brought to light that "immutability" is a word that shouldn't be used lightly. 

In the case of READ-ONLY attributes, these variables definitely aren't immutable: The variable can be changed from within the class, just not from outside. I have therefore removed the word "immutable" from the rule.

### CODE REVIEW

**Comment by ConjuringCoffee** [comment]
The build fails due to dead links which is unrelated to this change. I have fixed the links in #328.

**Comment by kjetil-kilhavn** [comment]
Dead links to abapGit documentation causes the build to fail, fixed in #329

**Review by sautermi0 — APPROVED** [review]

**Review by rdibbern — CHANGES_REQUESTED** [review]

**Review by N2oB6n-SAP — CHANGES_REQUESTED** [review]
I believe this PR misses the point of the original section. Admittedly, the original title is badly worded. Instead of "_Consider using immutable instead of getter_" what was meant is probably "_Use READ-ONLY attributes instead of getters for immutable objects_". "Immutable" itself is just an adjective so "consider using immutable" doesn't make much sense in the first place. Please bear with me as I attempt to untangle what's going on here:

1. We have `READ-ONLY` in ABAP and it generally should be used sparingly as highlighted in another section. Considering that it can only be used in a `PUBLIC SECTION` and public access should always be goverened by interfaces, though, I would hope to not encounter it very often in a clean and easily testable codebase.
2. There is the notion of [immutable objects](https://en.wikipedia.org/wiki/Immutable_object). These are so simple that using getters can very well be considered bloat. For a related pattern/concept see also: [Value object](https://en.wikipedia.org/wiki/Value_object)
3. "Immutability" is indeed a tricky term when it comes to ABAP where `READ-ONLY` and `FINAL` may not quite behave as one could reasonably expect coming from other programming languages.

In the light of **3** we should indeed be wary of the wording in this guide. I believe that the original author of the changed section was thinking of **2**. I agree with the original code example and the description text (note "An immutable is an object that [...]") as it greatly simplifies the object design. If we generalize it as proposed in this PR, however, we would effectively introduce a new rule that favors read-only public attributes over getter methods (which I personally would not approve).

**Comment by ConjuringCoffee** [comment]
Interesting! I think I misunderstood the intention of the original chapter. I rephrased the rule again to hopefully get the original intention across. 

I've turned the pull request into a draft because there's one thing left that I'd like to get some feedback on. Regarding this:

> Considering that it can only be used in a PUBLIC SECTION and public access should always be goverened by interfaces, though, I would hope to not encounter it very often in a clean and easily testable codebase.

Should we address how interfaces should be considered with this section? 
Interfaces can define attributes (including READ-ONLY attributes) too. It can be argued that the section currently proposes putting READ-ONLY attributes into interfaces. What do you think?

(Personally, I think interfaces should only define behavior and shouldn't contain any attributes, but some of my colleagues disagree. I don't think that Clean ABAP defines anything in this regard yet.)

**Comment by bjoern-jueliger-sap** [comment]
A `READ-ONLY` attribute in an interface to me is the same behavior specification as having a getter method, with the *additional* constraint that the result of the getter must not be computed at run time. This can make sense in application where getting this value from the interface is performance critical and you want to prevent someone messing up the performance of your application by (intentionally or unintentionally) writing an expensive implementation for the getter.

That is, the rule for using `READ-ONLY` in classes and interfaces should be exactly the same: Use it if and only if a getter method is unacceptable for performance reasons.

**Comment by pokrakam** [comment]
Interesting discussion, but I feel that immutability and writability should not be mixed up as they are here, they're very different ideas. READ-ONLY only applies to external consumers. If we do need to expose an attribute as PUBLIC then it is recommended to make it READ-ONLY for stability reasons.
As Bjoern already said, performance is one reason we may want to make an attribute public for the odd critical bottleneck. There are some technical scenarios too, e.g. use in Sapscript, or components that show attributes (common in workflow), there are some mapping features in various places that let you connect a class attribute to things. I think all these scenarios are what READ-ONLY is intended for.

**Comment by bjoern-jueliger-sap** [comment]
Caution: `final` can *only* be used in inline declarations for local variables, it is not an alternative to `read-only`, since `read-only` applies only to public attributes of a class. Every variable that can be made `read-only` cannot be made `final` and vice versa.

The "immutable objects" part should perhaps carry a performance hint: Im my tests, creating a bunch of plain data objects is between 4 and 10 times faster than creating the same number of instances of an object that holds the same data as `read-only` public attributes, and accessing the `read-only` attributes is 25% slower than accessing the component of the equivalent plain data object. So if these objects are the *main kind of object* your application processes, then you might find that switching out your data structures for classes with `read-only` attributes slows down your application.

**Comment by ConjuringCoffee** [comment]
I've reworked the text again, but ended up with something very close to the original. The original is quite broad, but in turn doesn't need all the nuances introduced when referring to the `READ-ONLY` or `FINAL` keywords. 

I think it's for the best to close this pull request without any further changes.

**Pull request closed without merging**
