### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by learnin**
Thanks for your great work.
Clean ABAP is a great guide and I believe this Japanese version will help more developers.
I hope you will merge this.

### CODE REVIEW

**Comment by HrFlorianHoffmann** [comment]
Sorry for the delay! Too many people in vacation over summer. 😀 It's now merged!

**Comment by KlausHaeuptleSAP** [comment]
@learnin: Thanks a lot for your contribution. I would like to publish a blog post on the translations and the contributors. Could you add a few sentences on your motivation for contributing the translation?

**Comment by learnin** [comment]
@KlausHaeuptleSAP As a beginner in SAP, I was looking for a good way to write ABAP code, and I found this guide based on Uncle Bob's Clean Code, which I am familiar with. After reading the guide, I decided to translate it not only to write my own code, but also to spread this modern code style to my company and Japanese ABAPers.

**Comment by KlausHaeuptleSAP** [comment]
@learnin: Thanks! Is it ok if I add the two sentences as a quote in the blog?

**Pull request merged**
